#!/usr/bin/env python3
"""Check for model performance metrics files in S3 and locally."""

import sys
import subprocess
from pathlib import Path
from collections import defaultdict

sys.stdout.reconfigure(encoding='utf-8')

cohorts = {
    'opioid_ed': ['13-24', '25-44', '45-54', '55-64'],
    'non_opioid_ed': ['65-74', '75-84', '85-94']
}

# Check S3 for performance files
print("="*80)
print("CHECKING S3 FOR MODEL PERFORMANCE FILES")
print("="*80)
print()

s3_performance_files = defaultdict(lambda: defaultdict(list))

for cohort, age_bands in cohorts.items():
    for age_band in age_bands:
        age_band_fname = age_band.replace('-', '_')
        
        # Check S3 paths
        s3_paths = [
            f"gold/final_model/{cohort}/{age_band}/",
            f"gold/final_model/{cohort}/{age_band_fname}/",
        ]
        
        for s3_base in s3_paths:
            try:
                result = subprocess.run(
                    ['aws', 's3', 'ls', f's3://pgxdatalake/{s3_base}', '--profile', 'mushin', '--recursive'],
                    capture_output=True,
                    text=True
                )
                
                for line in result.stdout.split('\n'):
                    if line.strip():
                        parts = line.split()
                        if len(parts) >= 4:
                            filename = parts[-1]
                            if any(x in filename.lower() for x in ['mc_cv', 'performance', 'metrics', 'evaluation', 'summary', 'results']):
                                s3_performance_files[cohort][age_band].append(filename)
            except Exception as e:
                pass

# Check local paths
print("Checking local model outputs...")
local_performance_files = defaultdict(lambda: defaultdict(list))

for cohort, age_bands in cohorts.items():
    for age_band in age_bands:
        age_band_fname = age_band.replace('-', '_')
        
        # Check local output directories
        local_paths = [
            Path(f"6_final_model/outputs/{cohort}/{age_band_fname}"),
            Path(f"6_final_model/model_outputs/{cohort}/{age_band_fname}"),
        ]
        
        for local_dir in local_paths:
            if local_dir.exists():
                for pattern in ['*mc_cv*.csv', '*performance*.json', '*metrics*.json', '*summary*.txt', '*evaluation*.json']:
                    for f in local_dir.rglob(pattern):
                        local_performance_files[cohort][age_band].append(str(f.relative_to(Path('.'))))

# Print results
print("\n" + "="*80)
print("MODEL PERFORMANCE FILES STATUS")
print("="*80)
print()

all_found = True
for cohort, age_bands in cohorts.items():
    print(f"{cohort.upper()}:")
    for age_band in age_bands:
        print(f"  {age_band}:")
        
        s3_files = s3_performance_files[cohort][age_band]
        local_files = local_performance_files[cohort][age_band]
        
        if s3_files:
            print(f"    S3 files found:")
            for f in s3_files:
                print(f"      - {f}")
        else:
            print(f"    [NO S3 PERFORMANCE FILES]")
        
        if local_files:
            print(f"    Local files found:")
            for f in local_files:
                print(f"      - {f}")
        else:
            print(f"    [NO LOCAL PERFORMANCE FILES]")
        
        if not s3_files and not local_files:
            all_found = False
        print()

print("="*80)
if all_found:
    print("STATUS: Some performance files found")
else:
    print("STATUS: No performance files found in expected locations")
    print()
    print("Note: MC-CV results may be stored in model output directories")
    print("or may need to be generated by running model training.")
print("="*80)
