#!/usr/bin/env python3
"""
Generate QR codes for PharmGKB VIP pages (now on ClinPGx).

Migrated from R scripts (PGx.Rmd) to Python.
Updates:
- QR codes now point to https://www.clinpgx.org/vip/{PA_ID}/overview
- Uses qrcode library instead of R's qrcode package
"""

import json
from pathlib import Path
from typing import List, Dict
import qrcode
from PIL import Image


def generate_qr_code(url: str, output_path: Path, size: int = 200):
    """
    Generate QR code PNG for a given URL.
    
    Args:
        url: Target URL for QR code
        output_path: Path to save PNG file
        size: QR code size in pixels (default 200x200)
    """
    # Create QR code instance
    qr = qrcode.QRCode(
        version=1,  # Controls size (1-40)
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    
    # Add data and generate
    qr.add_data(url)
    qr.make(fit=True)
    
    # Create image
    img = qr.make_image(fill_color="black", back_color="white")
    
    # Resize to target size
    img = img.resize((size, size), Image.Resampling.LANCZOS)
    
    # Save
    output_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(output_path)


def generate_qr_codes_from_vip_data(
    vip_data: List[Dict],
    output_dir: Path,
    size: int = 200
) -> List[Dict]:
    """
    Generate QR codes for all VIP genes.
    
    Args:
        vip_data: List of VIP gene dicts with 'vip_url' and 'qr_filename' keys
        output_dir: Directory to save QR code PNGs
        size: QR code size in pixels
    
    Returns:
        List of dicts mapping gene symbol to QR code path
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    qr_mappings = []
    
    for gene_entry in vip_data:
        gene_symbol = gene_entry.get("gene", "")
        vip_url = gene_entry.get("vip_url", "")
        qr_filename = gene_entry.get("qr_filename", f"{gene_symbol}.png")
        
        if not vip_url or not gene_symbol:
            print(f"Skipping {gene_symbol}: missing URL or symbol")
            continue
        
        # Generate QR code
        qr_path = output_dir / qr_filename
        try:
            generate_qr_code(vip_url, qr_path, size=size)
            print(f"✓ Generated QR code for {gene_symbol} -> {qr_path.name}")
            
            qr_mappings.append({
                "gene": gene_symbol,
                "vip_url": vip_url,
                "qr_path": str(qr_path),
                "qr_filename": qr_filename
            })
        except Exception as e:
            print(f"✗ Error generating QR code for {gene_symbol}: {e}")
    
    return qr_mappings


def load_vip_data(vip_json_path: Path) -> List[Dict]:
    """Load VIP data from JSON file (generated by fetch_pharmgkb_data.py)."""
    if not vip_json_path.exists():
        raise FileNotFoundError(
            f"VIP data not found: {vip_json_path}\n"
            "Run fetch_pharmgkb_data.py first to generate VIP gene data."
        )
    
    with open(vip_json_path, encoding="utf-8") as f:
        return json.load(f)


def main():
    """Generate QR codes for all VIP genes."""
    # Paths
    script_dir = Path(__file__).parent
    data_dir = script_dir / "data"
    qr_output_dir = script_dir / "qr_codes"
    
    vip_json = data_dir / "pharmgkb_vip_genes.json"
    qr_mappings_json = data_dir / "qr_code_mappings.json"
    
    # Load VIP data
    print("Loading VIP gene data...")
    vip_data = load_vip_data(vip_json)
    print(f"Found {len(vip_data)} VIP genes")
    
    # Generate QR codes
    print("\nGenerating QR codes...")
    qr_mappings = generate_qr_codes_from_vip_data(vip_data, qr_output_dir)
    
    # Save mappings
    with open(qr_mappings_json, "w", encoding="utf-8") as f:
        json.dump(qr_mappings, f, indent=2, ensure_ascii=False)
    
    print(f"\n✓ Generated {len(qr_mappings)} QR codes in {qr_output_dir}")
    print(f"✓ Saved mappings to {qr_mappings_json}")


if __name__ == "__main__":
    main()
